// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuHBD9q4YNmtiglsEdTUmf0vBSokm5gw',
    appId: '1:508531868967:web:44e4c00273ada74245d502',
    messagingSenderId: '508531868967',
    projectId: 'spotify-33c8b',
    authDomain: 'spotify-33c8b.firebaseapp.com',
    storageBucket: 'spotify-33c8b.firebasestorage.app',
    measurementId: 'G-2EZE9SHHXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhygptthu4ZHLqBGfDkmjwzOD2tkIXa3o',
    appId: '1:508531868967:android:d9c6b57f6588615b45d502',
    messagingSenderId: '508531868967',
    projectId: 'spotify-33c8b',
    storageBucket: 'spotify-33c8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLS1FWj02PQZG7XEI7O9W2qKHPtlLh5k',
    appId: '1:508531868967:ios:25f1deb118d7143945d502',
    messagingSenderId: '508531868967',
    projectId: 'spotify-33c8b',
    storageBucket: 'spotify-33c8b.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxLS1FWj02PQZG7XEI7O9W2qKHPtlLh5k',
    appId: '1:508531868967:ios:25f1deb118d7143945d502',
    messagingSenderId: '508531868967',
    projectId: 'spotify-33c8b',
    storageBucket: 'spotify-33c8b.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZuHBD9q4YNmtiglsEdTUmf0vBSokm5gw',
    appId: '1:508531868967:web:c50171be89d4aed045d502',
    messagingSenderId: '508531868967',
    projectId: 'spotify-33c8b',
    authDomain: 'spotify-33c8b.firebaseapp.com',
    storageBucket: 'spotify-33c8b.firebasestorage.app',
    measurementId: 'G-GL4K4JCQP9',
  );
}
